name: image_morpher
description: A simple image morpher app with local ML background removal.
publish_to: 'none' # Not published on pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # Image and file handling
  image_picker: ^1.0.4 #image_picker: ^0.8.7+5
  image: ^4.5.4
  path_provider: ^2.1.2
  camera: ^0.10.5+7

  # Local ML background remover
  local_rembg: ^1.1.3

  # Saving to gallery/media
  flutter_media_store: ^1.3.1

  # Permissions
  permission_handler: ^11.3.1

  # Networking (optional)
  http: ^1.4.0

  # Map Location and URL Launcher
  location: ^5.0.3
  url_launcher: ^6.2.5
  qr_flutter: ^4.0.0

  # For sharing to WhatsApp, Instagram, etc.
  share_plus: ^7.2.1  
  font_awesome_flutter: ^10.5.0  # For social media icons

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
  assets:
    - assets/images/MapMe.png
    - assets/images/TravelBuild.png
    - assets/images/BarbieBuild.png
    - assets/images/Camera.png